(()=>{'use strict';
const KEY='nodeimage_apiKey', ENABLED='nodeimage_enabled';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const state={enabled:true,toast:null,boundToolbars:new WeakSet(),boundEditors:new WeakSet(),queue:Promise.resolve(),busy:0,authRequired:false,keyAvailable:false,headerOverride:null,manager:null};
const send=p=>new Promise(resolve=>chrome.runtime.sendMessage(p,r=>resolve(r||{ok:false,error:chrome.runtime.lastError?.message||'扩展后台无响应'})));
async function loadEnabled(){const o=await chrome.storage.local.get([ENABLED,KEY]);state.enabled=o[ENABLED]!==false;state.keyAvailable=Boolean(o[KEY]);}
chrome.storage.onChanged.addListener((c,a)=>{if(a!=='local')return;if(c[ENABLED]){state.enabled=c[ENABLED].newValue!==false;if(!state.enabled)setAuthRequired(false);refreshHeaderEntry();}if(c[KEY]){state.keyAvailable=Boolean(c[KEY].newValue);if(state.keyAvailable)setAuthRequired(false);refreshHeaderEntry();}});
function toast(text,type='info',ttl=1800,action=null){let el=state.toast;if(!el){el=document.createElement('div');el.className='nodeimage-toast';document.body.appendChild(el);state.toast=el;}el.className=`nodeimage-toast ${type} show${action?' actionable':''}`;el.replaceChildren();const m=document.createElement('span');m.className='nodeimage-toast-message';m.textContent=text;el.appendChild(m);if(action||type==='error'){const a=document.createElement('span');a.className='nodeimage-toast-actions';if(action){const go=document.createElement('button');go.type='button';go.textContent=action.label;go.onclick=e=>{e.preventDefault();e.stopPropagation();action.onClick();};a.appendChild(go);}if(type==='error'){const cp=document.createElement('button');cp.type='button';cp.textContent='复制';cp.onclick=async()=>{try{await navigator.clipboard.writeText(text);cp.textContent='已复制';}catch(_){}};a.appendChild(cp);}const cl=document.createElement('button');cl.type='button';cl.textContent='关闭';cl.onclick=()=>el.classList.remove('show');a.appendChild(cl);el.appendChild(a);}clearTimeout(el._t);if(type!=='error'&&ttl>0)el._t=setTimeout(()=>el.classList.remove('show'),ttl);}
function openLogin(){window.open('https://www.nodeimage.com','_blank','noopener,noreferrer');}
function getHeaderSlot(){const a=document.querySelector('#editor-body .window_header a[href*="runoob.com/markdown"]');return a?.parentElement||null;}
function restoreHeader(){const o=state.headerOverride;if(o?.el?.isConnected){delete o.el.dataset.nsimgMode;o.el.innerHTML=o.html;}state.headerOverride=null;}
function managerSvg(){return '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 5.5A1.5 1.5 0 0 1 5.5 4h13A1.5 1.5 0 0 1 20 5.5v13a1.5 1.5 0 0 1-1.5 1.5h-13A1.5 1.5 0 0 1 4 18.5v-13Z"/><path d="m6.5 16 3.2-3.5 2.4 2.4 2.6-3 2.8 4.1"/><circle cx="9" cy="8.5" r="1.3"/></svg>';}
function refreshHeaderEntry(){const slot=getHeaderSlot()||state.headerOverride?.el;if(!slot||!slot.isConnected||!state.enabled){restoreHeader();return;}if(!state.authRequired&&!state.keyAvailable){restoreHeader();return;}if(!state.headerOverride||state.headerOverride.el!==slot){restoreHeader();state.headerOverride={el:slot,html:slot.innerHTML};}const mode=state.authRequired?'login':'manager';if(slot.dataset.nsimgMode===mode&&slot.querySelector('.nodeimage-header-entry'))return;slot.dataset.nsimgMode=mode;slot.replaceChildren();const b=document.createElement('button');b.type='button';b.className='nodeimage-header-entry';if(mode==='login'){b.classList.add('login');b.textContent='登录 NodeImage';b.title='登录 NodeImage';b.onclick=openLogin;}else{b.innerHTML=managerSvg()+'<span>图片</span>';b.title='管理 NodeImage 图片';b.onclick=openManager;}slot.appendChild(b);}
function setAuthRequired(v){state.authRequired=Boolean(v);if(v)state.keyAvailable=false;refreshHeaderEntry();}
async function ensureAuth({quiet=false}={}){const o=await chrome.storage.local.get(KEY);if(o[KEY]){state.keyAvailable=true;setAuthRequired(false);return true;}if(!quiet)toast('正在获取 NodeImage API Key…','info',10000);const r=await send({type:'NODEIMAGE_REFRESH_KEY'});if(r?.ok&&r.key){state.keyAvailable=true;setAuthRequired(false);if(!quiet)toast('已获取 API Key','success');return true;}if(r?.authRequired){setAuthRequired(true);if(!quiet)toast('请先登录 NodeImage','warning',5000,{label:'去登录',onClick:openLogin});return false;}state.keyAvailable=false;setAuthRequired(false);if(!quiet)toast('未获取到 API Key，可点击扩展图标重试或手动填写','warning',4200);return false;}
function fileToBase64(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>{const s=String(r.result||'');res(s.slice(s.indexOf(',')+1));};r.onerror=()=>rej(r.error||new Error('读取图片失败'));r.readAsDataURL(file);});}
async function upload(file,retry=0){try{if(!file||file.size===0)throw new Error(`图片为空（${file?.type||'未知 MIME'}）`);const base64=await fileToBase64(file);const r=await send({type:'NODEIMAGE_UPLOAD',name:file.name||'clipboard',mime:file.type||'',size:file.size,base64});if(!r.ok){if(/API Key 已失效|未获取到 API Key|HTTP 401|HTTP 403/i.test(r.error||''))setAuthRequired(true);throw new Error(r.error||'上传失败');}const d=r.data;if(d?.success&&d?.links?.markdown){state.keyAvailable=true;setAuthRequired(false);return d.links;}throw new Error(d?.error||d?.message||'NodeImage 返回上传失败');}catch(e){if(retry<2&&!/API Key|HTTP 400|HTTP 401|HTTP 403|图片为空|无法识别/i.test(String(e.message))){toast(`上传失败，正在重试 ${retry+1}/2`,'warning',1600);await sleep(1000);return upload(file,retry+1);}throw e;}}
function insertMarkdown(md){const markdown=`\n${md}\n`;const ta=document.activeElement;if(ta?.tagName==='TEXTAREA'&&!ta.closest('.CodeMirror')){ta.setRangeText(markdown,ta.selectionStart,ta.selectionEnd,'end');ta.dispatchEvent(new Event('input',{bubbles:true}));return Promise.resolve(true);}return new Promise(resolve=>{const id=`${Date.now()}-${Math.random()}`;const done=e=>{if(e.detail?.id!==id)return;clearTimeout(timer);document.removeEventListener('nsimg:insert-result',done);resolve(Boolean(e.detail.ok));};document.addEventListener('nsimg:insert-result',done);const timer=setTimeout(()=>{document.removeEventListener('nsimg:insert-result',done);resolve(false);},1200);document.dispatchEvent(new CustomEvent('nsimg:insert-markdown',{detail:{id,markdown}}));});}
async function processFiles(files){if(!state.enabled)return;const imgs=[...files].filter(f=>f&&((f.type||'').startsWith('image/')||/\.(png|jpe?g|gif|webp|bmp)$/i.test(f.name||'')));if(!imgs.length)return;if(!(await ensureAuth()))return;state.busy++;document.documentElement.classList.add('nodeimage-uploading');try{for(let i=0;i<imgs.length;i++){toast(imgs.length>1?`正在上传 ${i+1}/${imgs.length}…`:'正在上传…','info',60000);const links=await upload(imgs[i]);if(!(await insertMarkdown(links.markdown)))throw new Error('图片已上传，但未能插入编辑器；请在 NodeImage 图片管理中找回链接');}toast(imgs.length>1?`${imgs.length} 张图片上传成功`:'图片上传成功','success');}catch(e){toast(String(e.message).startsWith('图片已上传')?e.message:`上传失败：${e.message}`,'error',0);}finally{state.busy--;if(!state.busy)document.documentElement.classList.remove('nodeimage-uploading');}}
function enqueue(files){state.queue=state.queue.then(()=>processFiles(files)).catch(e=>toast(`上传失败：${e.message}`,'error',0));return state.queue;}
function isEditing(){const a=document.activeElement;return !!(a&&(a.closest?.('.CodeMirror')||a.tagName==='TEXTAREA'));}
function paste(e){if(!state.enabled||!isEditing())return;const dt=e.clipboardData||e.originalEvent?.clipboardData;if(!dt)return;let files=[];if(dt.files?.length)files=[...dt.files].filter(f=>(f.type||'').startsWith('image/'));if(!files.length&&dt.items?.length)files=[...dt.items].filter(i=>i.kind==='file'&&(i.type||'').startsWith('image/')).map(i=>i.getAsFile()).filter(Boolean);if(files.length){e.preventDefault();e.stopPropagation();enqueue(files);}}
function choose(){const i=document.createElement('input');i.type='file';i.multiple=true;i.accept='image/*';i.onchange=()=>i.files?.length&&enqueue(i.files);i.click();}
function wireToolbar(toolbar){if(state.boundToolbars.has(toolbar))return;const btn=toolbar.querySelector('.toolbar-item.i-icon-pic[title="图片"],.toolbar-item[title="图片"]');if(!btn)return;state.boundToolbars.add(toolbar);btn.dataset.nodeimageBound='1';btn.addEventListener('click',e=>{if(!state.enabled)return;e.preventDefault();e.stopImmediatePropagation();choose();},true);}
function wireEditor(editor){if(state.boundEditors.has(editor))return;state.boundEditors.add(editor);editor.addEventListener('dragover',e=>{if(!state.enabled)return;const items=[...(e.dataTransfer?.items||[])];if(items.some(i=>(i.type||'').startsWith('image/'))){e.preventDefault();e.dataTransfer.dropEffect='copy';}});editor.addEventListener('drop',e=>{if(!state.enabled)return;const files=[...(e.dataTransfer?.files||[])].filter(f=>(f.type||'').startsWith('image/'));if(files.length){e.preventDefault();enqueue(files);}});}
function normalizeImages(data){let a=Array.isArray(data)?data:(data?.images||data?.data||data?.items||data?.results||[]);if(!Array.isArray(a))a=[];return a.map((x,i)=>{const links=x?.links||{};const url=x?.url||x?.image_url||x?.imageUrl||x?.direct_url||x?.directUrl||links.direct||links.url||links.original||links.image||'';const thumb=x?.thumbnail_url||x?.thumbnailUrl||x?.thumb_url||x?.thumbUrl||links.thumbnail||links.thumb||url;const id=x?.id||x?.image_id||x?.imageId||x?.uuid||x?.key||'';const markdown=links.markdown||x?.markdown||(url?`![](${url})`:'');return{id:String(id),url:String(url),thumb:String(thumb),markdown:String(markdown),raw:x,index:i};}).filter(x=>x.url||x.thumb);}
function closeManager(){state.manager?.remove();state.manager=null;}
function eyeSvg(){return '<svg viewBox="0 0 24 24"><path d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6-9.5-6-9.5-6Z"/><circle cx="12" cy="12" r="2.7"/></svg>';}
function trashSvg(){return '<svg viewBox="0 0 24 24"><path d="M4 7h16M9 7V4h6v3m3 0-1 13H7L6 7m4 4v5m4-5v5"/></svg>';}
async function openManager(){if(!(await ensureAuth()))return;if(state.manager){state.manager.classList.add('show');return;}const root=document.createElement('div');root.className='nodeimage-manager show';root.innerHTML='<div class="nodeimage-manager-backdrop"></div><section class="nodeimage-manager-panel" role="dialog" aria-modal="true"><header><div><strong>NodeImage 图片</strong><small>点击图片插入到编辑器</small></div><button class="nodeimage-manager-close" title="关闭">×</button></header><div class="nodeimage-manager-body"><div class="nodeimage-manager-loading">正在加载图片…</div></div></section>';document.body.appendChild(root);state.manager=root;root.querySelector('.nodeimage-manager-backdrop').onclick=closeManager;root.querySelector('.nodeimage-manager-close').onclick=closeManager;const body=root.querySelector('.nodeimage-manager-body');try{const r=await send({type:'NODEIMAGE_LIST'});if(!r.ok){if(r.authRequired)setAuthRequired(true);throw new Error(r.error||'获取图片列表失败');}const images=normalizeImages(r.data);if(!images.length){body.innerHTML='<div class="nodeimage-manager-empty">还没有上传图片</div>';return;}body.replaceChildren();const grid=document.createElement('div');grid.className='nodeimage-image-grid';for(const img of images){const card=document.createElement('div');card.className='nodeimage-image-card';const im=document.createElement('img');im.loading='lazy';im.src=img.thumb||img.url;im.alt='NodeImage';im.title='点击插入图片';im.onclick=async()=>{if(!img.markdown)return;if(await insertMarkdown(img.markdown)){toast('图片链接已插入','success');closeManager();}else toast('未找到可插入图片链接的编辑器','error',0);};card.appendChild(im);const tools=document.createElement('div');tools.className='nodeimage-image-tools';const view=document.createElement('button');view.type='button';view.title='查看大图';view.innerHTML=eyeSvg();view.onclick=e=>{e.stopPropagation();window.open(img.url,'_blank','noopener,noreferrer');};tools.appendChild(view);if(img.id){const del=document.createElement('button');del.type='button';del.title='删除图片';del.className='danger';del.innerHTML=trashSvg();del.onclick=async e=>{e.stopPropagation();if(!confirm('确定删除这张图片吗？删除后无法恢复。'))return;del.disabled=true;const d=await send({type:'NODEIMAGE_DELETE',id:img.id});if(d.ok){card.remove();toast('图片已删除','success');if(!grid.children.length)body.innerHTML='<div class="nodeimage-manager-empty">还没有上传图片</div>';}else{del.disabled=false;if(d.authRequired)setAuthRequired(true);toast(`删除失败：${d.error||'未知错误'}`,'error',0);}};tools.appendChild(del);}card.appendChild(tools);grid.appendChild(card);}body.appendChild(grid);}catch(e){body.innerHTML='';const err=document.createElement('div');err.className='nodeimage-manager-empty';err.textContent=`加载失败：${e.message}`;body.appendChild(err);}}
function scan(){document.querySelectorAll('.mde-toolbar').forEach(wireToolbar);document.querySelectorAll('.CodeMirror').forEach(wireEditor);refreshHeaderEntry();}
async function init(){await loadEnabled();document.addEventListener('paste',paste,true);scan();new MutationObserver(scan).observe(document.body,{childList:true,subtree:true});if(state.enabled&&!state.keyAvailable)ensureAuth({quiet:true}).then(refreshHeaderEntry);}
init();})();
